# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Miss-Managr
tagline:          redefining productivity
url:              http://miss-managr.com
paginate:         1
baseurl:          /
author:
  name:           Gertie Belcher
  url:            https://twitter.com/GertieBelcher
  email:          satiricallaughter@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
