# Dependencies
markdown:         redcarpet
pygments:         true
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

# Permalinks
# permalink:        This is set in each blog post

paginate:         1
#paginate_path:    permalink

# Setup
title:            Miss-Managr
tagline:          redefining productivity
url:              http://miss-managr.com
baseurl:          /
author:
  name:           Gertie Belcher
  url:            https://twitter.com/GertieBelcher
  email:          satiricallaughter@gmail.com

#
pages_list:       
  Archive: '/archive'

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole